### ISSUE TITLE
Move google forms onto the site

### ISSUE THREAD

**Issue by saikat** [BrandNewCongress/website#2] opened 2016-12-12 15:22 UTC
Port over external forms currently on Google, to be local forms on BNC. 
* Create a new page on the BNC site (via the admin) and create necessary custom file in vhost based on the new page ID.
* Reference the existing form on BNC for an example of how to use Angular and Sitetheory to easily make a form: `/Sitetheory/ArticleBundle/Resources/views/Article35633.html.twig`
* Use the styles from BNC as established in existing forms.

1. Port over the Volunteer Special Skills form from [Justice Democrate](https://justicedemocrats.com/volunteer-skills/) to BNC. Reference structure and field name variables from JD example form.

2. two other forms including backend coding... to be determined by @saikat

**Comment by chadwickmeyer** [comment] 2017-02-09 00:31
Volunteers Form is in progress. https://bnc.sitetheory.net/Volunteer-Skills
Sent test submission. Need to confirm all fields were received successfully.

`{"utmCampaign":null,"utmSource":"bnc.sitetheory.net","utmMedium":null,"volunteerName":"Test","volunteerEmail":"test@test.com","volunteerPhone":"5555555555","volunteerAddress":"100 test","volunteerCity":"Walnut Creek","volunteerState":"CA","volunteerZip":"94598","volunteerLinkedIn":"linkedin.com/in/tester","volunteerSkills":["skill-programming","skill-web-design","skill-graphic-design","skill-video","skill-writing","skill-press","skill-nationbuilder","skill-data-entry","skill-call","skill-helpdesk","skill-sharing","skill-printing","skill-travel","skill-hr","skill-legal","skill-manage-communities","skill-supporter-housing","skill-event-host","skill-venue"],"volunteerProfile":"I've checked every box, so make sure those values line up with your expected values."}`

**Comment by chadwickmeyer** [comment] 2017-02-09 00:50
Volunteer form completed, tested, and confirmed to be working.

**Comment by chadwickmeyer** [comment] 2017-02-09 00:56
There are additional forms and resources that are currently hosted externally (mostly on Google docs), which need to be ported over to the website.

The forms need to connect to an API, which means someone (with the guidance of @saikat) need to create the API connection point and variables. Update this list with the URL, and list of variables for each form field as they are created. If someone builds the form first, create the field names based on existing standards for other fields (camelCase) and add the fields here for the API builder.

Whenever a resources moved over, the codebase needs to be searched to update links to go to the new local page.

Forms
=====

District Research
https://docs.google.com/forms/d/e/1FAIpQLSe8CfK0gUULEVpYFm9Eb4iyGOL-_iDl395qB0z4hny7ek4iNw/viewform

Suggest Local Connector
https://docs.google.com/forms/d/e/1FAIpQLSceYguZI_gngXf7dLOXN6xUkLRNsYfn0b2v-aDEvZKPH-j1dQ/viewform


Resources
========

Organize Locally (just local files, probably should be zipped and provided as a PDF download)
https://docs.google.com/document/d/1Op0OaZNuykCJckSCn4vABDEr4VEdTrMeTsPCZFNSJo4/edit

Candidate Nomination Guide:
https://docs.google.com/document/d/1_Aob44aXGpc6OVOxzLNMSW-9_Hs7m5nghKYBGoeuUlE/edit

Plan to Rebuild America (keep external ATM since it's changing a lot)
https://docs.google.com/document/d/1sCFs5hqitbXBBqXxU6NULDyvydXqm-ALOqW21dv9P9k/edit

**Comment by chadwickmeyer** [comment] 2017-02-09 00:58
Closing and creating new Issue for the remaining ports. See issue: https://github.com/BrandNewCongress/website/issues/21

**Closed as completed by chadwickmeyer** 2017-02-09 00:58 UTC

**Comment by chadwickmeyer** [comment] 2017-02-09 01:27
Form was rolled back temporarily till some additional fields are put into place. See https://github.com/BrandNewCongress/website/issues/22
